// GENERATED by tools/game-builtin-extract.sh --write — do not edit.
//
// The fight constants the engine's `getCellContent` answers with, from
// `crates/core/leek-environment/game_constants.tsv` (itself extracted from
// the generator's `FightConstants.java`). The language side resolves and
// folds the same names from that table, so generating them here keeps the
// engine's answers and the AI's constants on one source of truth.
//
// `CELL_PLAYER` is upstream's deprecated alias of `CELL_ENTITY`: both are 1.
pub const CELL_EMPTY: i64 = 0;
pub const CELL_ENTITY: i64 = 1;
pub const CELL_OBSTACLE: i64 = 2;
pub const CELL_PLAYER: i64 = 1;
