// GENERATED by tools/game-item-extract.sh --write — do not edit.
//
// The weapon catalog from the generator's `data/weapons.json`,
// keyed by the public `WEAPON_*` item id, sorted by item id.
#[rustfmt::skip]
static CATALOG: &[Weapon] = &[
    Weapon { item: 37, name: "pistol", cost: 3, min_range: 1, max_range: 7, launch_type: 1, area: 1, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 15.0, 5.0, 0, 31, 0)] },
    Weapon { item: 38, name: "machine_gun", cost: 4, min_range: 1, max_range: 6, launch_type: 0, area: 1, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 10.0, 5.0, 0, 31, 0), Effect::from_upstream(1, 10.0, 5.0, 0, 31, 0), Effect::from_upstream(1, 10.0, 5.0, 0, 31, 0)] },
    Weapon { item: 39, name: "double_gun", cost: 4, min_range: 2, max_range: 7, launch_type: 1, area: 1, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 18.0, 7.0, 0, 31, 0), Effect::from_upstream(13, 7.0, 3.0, 2, 31, 1)] },
    Weapon { item: 40, name: "destroyer", cost: 6, min_range: 1, max_range: 6, launch_type: 1, area: 1, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 40.0, 20.0, 0, 31, 0), Effect::from_upstream(19, 12.0, 0.0, 2, 31, 1)] },
    Weapon { item: 41, name: "shotgun", cost: 5, min_range: 1, max_range: 5, launch_type: 0, area: 1, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 33.0, 10.0, 0, 31, 0), Effect::from_upstream(27, 20.0, 0.0, 1, 31, 1)] },
    Weapon { item: 42, name: "laser", cost: 6, min_range: 2, max_range: 9, launch_type: 0, area: 2, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 43.0, 16.0, 0, 31, 0)] },
    Weapon { item: 43, name: "grenade_launcher", cost: 6, min_range: 4, max_range: 7, launch_type: 1, area: 4, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 45.0, 8.0, 0, 31, 0)] },
    Weapon { item: 44, name: "electrisor", cost: 7, min_range: 7, max_range: 7, launch_type: 1, area: 3, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 70.0, 10.0, 0, 31, 0)] },
    Weapon { item: 45, name: "magnum", cost: 5, min_range: 1, max_range: 8, launch_type: 1, area: 1, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 25.0, 15.0, 0, 31, 0)] },
    Weapon { item: 46, name: "flame_thrower", cost: 6, min_range: 2, max_range: 8, launch_type: 0, area: 2, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 35.0, 5.0, 0, 31, 0), Effect::from_upstream(13, 24.0, 6.0, 2, 31, 1)] },
    Weapon { item: 47, name: "m_laser", cost: 8, min_range: 5, max_range: 12, launch_type: 0, area: 2, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 90.0, 10.0, 0, 31, 0)] },
    Weapon { item: 48, name: "gazor", cost: 8, min_range: 2, max_range: 7, launch_type: 0, area: 5, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(13, 27.0, 5.0, 3, 31, 1)] },
    Weapon { item: 60, name: "b_laser", cost: 5, min_range: 2, max_range: 8, launch_type: 0, area: 2, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 50.0, 10.0, 0, 31, 0), Effect::from_upstream(2, 50.0, 10.0, 0, 31, 0)] },
    Weapon { item: 107, name: "katana", cost: 7, min_range: 1, max_range: 1, launch_type: 1, area: 1, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 77.0, 0.0, 0, 31, 0), Effect::from_upstream(19, 10.0, 0.0, 1, 31, 1), Effect::from_upstream(17, 0.2, 0.1, 1, 31, 1), Effect::from_upstream(18, 0.2, 0.1, 1, 31, 1)] },
    Weapon { item: 108, name: "broadsword", cost: 5, min_range: 1, max_range: 1, launch_type: 1, area: 1, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 39.0, 2.0, 0, 31, 0), Effect::from_upstream(38, 50.0, 0.0, 2, 31, 5)] },
    Weapon { item: 109, name: "axe", cost: 6, min_range: 1, max_range: 1, launch_type: 1, area: 1, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 44.0, 33.0, 0, 31, 0), Effect::from_upstream(17, 0.5, 0.1, 1, 31, 1)] },
    Weapon { item: 115, name: "j_laser", cost: 4, min_range: 5, max_range: 11, launch_type: 0, area: 2, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(27, 20.0, 0.0, 2, 31, 1), Effect::from_upstream(29, 20.0, 0.0, 2, 31, 5)] },
    Weapon { item: 116, name: "illicit_grenade_launcher", cost: 6, min_range: 4, max_range: 7, launch_type: 1, area: 4, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 10.0, 0.0, 0, 31, 0), Effect::from_upstream(1, 10.0, 0.0, 0, 31, 0), Effect::from_upstream(1, 10.0, 0.0, 0, 31, 0), Effect::from_upstream(1, 10.0, 0.0, 0, 31, 0)] },
    Weapon { item: 117, name: "mysterious_electrisor", cost: 7, min_range: 7, max_range: 7, launch_type: 1, area: 3, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(30, 34.0, 6.0, 0, 31, 1), Effect::from_upstream(26, 7.0, 0.0, 2, 31, 1)] },
    Weapon { item: 118, name: "unbridled_gazor", cost: 8, min_range: 2, max_range: 7, launch_type: 0, area: 5, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 69.0, 4.0, 0, 31, 0)] },
    Weapon { item: 119, name: "revoked_m_laser", cost: 8, min_range: 5, max_range: 12, launch_type: 0, area: 2, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(13, 50.0, 10.0, 2, 31, 1)] },
    Weapon { item: 151, name: "rifle", cost: 7, min_range: 7, max_range: 9, launch_type: 1, area: 1, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 73.0, 6.0, 0, 31, 0)] },
    Weapon { item: 153, name: "rhino", cost: 5, min_range: 2, max_range: 4, launch_type: 1, area: 1, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(1, 58.0, 6.0, 0, 31, 0)] },
    Weapon { item: 175, name: "explorer_rifle", cost: 7, min_range: 7, max_range: 9, launch_type: 1, area: 1, los: true, cooldown: 0, max_uses: 0, effects: &[Effect::from_upstream(2, 68.0, 8.0, 0, 31, 0)] },
];
