//! `miku fight --emit` — generate a self-contained native executable that runs
//! a fight and prints its outcome.
//!
//! The emitted program is a tiny Rust crate that embeds the fully-resolved
//! scenario (as JSON) and every AI's source, links the `leek-scenario` /
//! `leek-generator` engine, and compiles to one standalone binary. It needs
//! `cargo` (and this workspace's crates) at emit time; the resulting binary is
//! self-contained.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use anyhow::{bail, Context, Result};
use leek_scenario::Scenario;

/// Absolute path to this workspace's root, derived from miku's manifest dir.
fn workspace_root() -> Result<PathBuf> {
    let miku_manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    std::fs::canonicalize(miku_manifest.join("../.."))
        .context("locating the workspace root for engine crate paths")
}

const MAIN_TEMPLATE: &str = r#"//! Generated by `miku fight --emit`. Runs the baked-in fight and prints the winner.
use std::collections::HashMap;

use leek_scenario::Scenario;

const SCENARIO_JSON: &str = /*SCENARIO*/;
const AIS: &[(i64, &str)] = &[
/*AIS*/];

fn main() {
    if let Err(e) = run() {
        eprintln!("error: {e:#}");
        std::process::exit(1);
    }
}

fn run() -> anyhow::Result<()> {
    leek_recipes::load_and_register_libraries(["leekwars"]).map_err(|e| anyhow::anyhow!("{e}"))?;
    let scn = Scenario::from_json_str(SCENARIO_JSON)?;
    let world = leek_scenario::build_world(&scn)?;
    let mut ais = HashMap::new();
    for (id, src) in AIS {
        let hir = leek_scenario::compile_ai_source(src, "embedded", world.version, world.strict)?;
        ais.insert(*id, hir);
    }
    let fight = leek_generator::shared(world.fight);
    let outcome =
        leek_generator::run_fight_release(&fight, &ais, world.max_turns, world.version, world.strict)
            .map_err(|e| anyhow::anyhow!("fight error: {e}"))?;
    match outcome.winner_team {
        Some(t) => println!("winner: team {t} ({} turns)", outcome.turns),
        None => println!("draw ({} turns)", outcome.turns),
    }
    Ok(())
}
"#;

/// Generate, build, and install a standalone fight executable at `out`.
pub fn emit(scn: &Scenario, base_dir: &Path, out: &Path, quiet: bool) -> Result<()> {
    let root = workspace_root()?;

    // Collect each AI's source so the binary doesn't depend on external files.
    let mut ai_entries = String::new();
    for spec in &scn.entities {
        if let (Some(id), Some(ai)) = (spec.id, &spec.ai) {
            let path = base_dir.join(ai);
            let source = std::fs::read_to_string(&path)
                .with_context(|| format!("reading AI {}", path.display()))?;
            // `{:?}` renders a valid, fully-escaped Rust string literal.
            let _ = writeln!(ai_entries, "    ({id}, {source:?}),");
        }
    }
    let scenario_json =
        serde_json::to_string(scn).context("serializing the resolved scenario")?;

    let main_rs = MAIN_TEMPLATE
        .replace("/*SCENARIO*/", &format!("{scenario_json:?}"))
        .replace("/*AIS*/", &ai_entries);

    let cargo_toml = format!(
        r#"[package]
name = "fight_runner"
version = "0.0.0"
edition = "2024"

[[bin]]
name = "fight_runner"
path = "src/main.rs"

[dependencies]
leek-scenario  = {{ path = "{root}/crates/game/leek-scenario" }}
leek-generator = {{ path = "{root}/crates/game/leek-generator" }}
leek-recipes   = {{ path = "{root}/crates/db/leek-recipes" }}
anyhow = "1"

# Stand alone — don't attach to the engine workspace.
[workspace]
"#,
        root = root.display(),
    );

    // Lay out the generated crate in a temp project dir.
    let proj = std::env::temp_dir().join(format!("miku-fight-emit-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&proj);
    std::fs::create_dir_all(proj.join("src"))
        .with_context(|| format!("creating {}", proj.join("src").display()))?;
    std::fs::write(proj.join("Cargo.toml"), cargo_toml)?;
    std::fs::write(proj.join("src/main.rs"), main_rs)?;

    if !quiet {
        eprintln!("miku: building standalone fight runner (cargo, release)…");
    }
    let status = Command::new("cargo")
        .arg("build")
        .arg("--release")
        .arg("--manifest-path")
        .arg(proj.join("Cargo.toml"))
        .stdin(Stdio::null())
        .stdout(if quiet { Stdio::null() } else { Stdio::inherit() })
        .stderr(Stdio::inherit())
        .status()
        .context("running `cargo build` (is cargo on PATH?)")?;
    if !status.success() {
        bail!("cargo build of the generated fight runner failed");
    }

    let built = proj.join("target/release/fight_runner");
    std::fs::copy(&built, out)
        .with_context(|| format!("installing executable to {}", out.display()))?;
    let _ = std::fs::remove_dir_all(&proj);

    if !quiet {
        eprintln!("miku: wrote executable to {}", out.display());
    }
    Ok(())
}
