[package]
name        = "leek-hir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "High-level intermediate representation for Leekscript."

[dependencies]
leek-span        = { workspace = true }
leek-visit       = { workspace = true }
leek-text        = { workspace = true }
leek-syntax      = { workspace = true }
leek-parser      = { workspace = true }
leek-diagnostics = { workspace = true }
leek-types       = { workspace = true }
leek-resolver    = { workspace = true }
leek-pipeline    = { workspace = true }
leek-prelude     = { workspace = true }
leek-config      = { workspace = true }
leek-environment = { workspace = true }
rowan            = { workspace = true }
num-bigint       = { workspace = true }
salsa            = { workspace = true }

[lints]
workspace = true
