//! `cargo xtask graph`: the workspace's crate graph, as a mermaid diagram.
//!
//! [`docs/architecture.md`] describes the layers in prose, which is exactly
//! the kind of description that drifts: a crate moved between layers, or a
//! new edge added, changes the graph and nothing makes the prose notice.
//! So the diagram is *generated* from `cargo metadata` and committed, and
//! `--check` fails when the committed copy no longer matches the workspace —
//! the same contract the other generated artifacts in this repository have.
//!
//! Only **normal** dependencies between workspace members are drawn. Build
//! and dev edges are real, and `check-layers` enforces its own rules on
//! them, but a picture that showed every test's reach up a layer would say
//! nothing about how the compiler is put together.
//!
//! [`docs/architecture.md`]: ../../docs/architecture.md

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::process::ExitCode;

use crate::layers::{DepKind, Workspace, load_workspace, workspace_root};

/// Where the generated diagram lives, relative to the workspace root.
const GRAPH_PATH: &str = "docs/crate-graph.md";

/// The mermaid document for `ws`: one subgraph per layer, in stack order,
/// and one arrow per normal dependency.
#[must_use]
pub fn render(ws: &Workspace) -> String {
    let mut by_layer: BTreeMap<u8, BTreeMap<&str, Vec<&str>>> = BTreeMap::new();
    for (name, layer) in &ws.crates {
        by_layer
            .entry(layer.rank())
            .or_default()
            .entry(layer.name())
            .or_default()
            .push(name);
    }

    let mut out = String::new();
    out.push_str(
        "# Crate graph\n\
         \n\
         <!-- Generated by `cargo xtask graph`. Do not edit by hand; run the\n\
         \x20    task and commit the result. `cargo xtask graph --check` fails\n\
         \x20    when this file and the workspace disagree. -->\n\
         \n\
         Normal dependencies between workspace members, grouped by layer.\n\
         Build and dev edges are left out: `cargo xtask check-layers` has its\n\
         own rules for those, and drawing every test's reach up a layer would\n\
         say nothing about how the compiler is put together.\n\
         \n\
         ```mermaid\n\
         graph BT\n",
    );
    for layers in by_layer.values() {
        for (layer, crates) in layers {
            let _ = writeln!(out, "  subgraph {layer}");
            for name in crates {
                let _ = writeln!(out, "    {}[\"{name}\"]", id(name));
            }
            out.push_str("  end\n");
        }
    }
    for edge in &ws.edges {
        if edge.kind == DepKind::Normal {
            let _ = writeln!(out, "  {} --> {}", id(&edge.from), id(&edge.to));
        }
    }
    out.push_str("```\n");
    out
}

/// A mermaid-safe node id: hyphens are operators there, underscores are not.
fn id(crate_name: &str) -> String {
    crate_name.replace('-', "_")
}

/// Entry point for `cargo xtask graph [--check]`.
pub fn run(check: bool) -> ExitCode {
    let ws = match load_workspace() {
        Ok(ws) => ws,
        Err(errors) => {
            for e in errors {
                eprintln!("graph: {e}");
            }
            return ExitCode::FAILURE;
        }
    };
    let rendered = render(&ws);
    let path = workspace_root().join(GRAPH_PATH);

    if !check {
        if let Err(e) = std::fs::write(&path, &rendered) {
            eprintln!("graph: cannot write {GRAPH_PATH}: {e}");
            return ExitCode::FAILURE;
        }
        println!("graph: wrote {GRAPH_PATH} ({} crates)", ws.crates.len());
        return ExitCode::SUCCESS;
    }

    match std::fs::read_to_string(&path) {
        Ok(committed) if committed == rendered => {
            println!("graph check: ok ({} crates)", ws.crates.len());
            ExitCode::SUCCESS
        }
        Ok(_) => {
            eprintln!(
                "graph check: {GRAPH_PATH} is out of date — run `cargo xtask graph` and \
                 commit the result"
            );
            ExitCode::FAILURE
        }
        Err(e) => {
            eprintln!("graph check: cannot read {GRAPH_PATH}: {e}");
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layers::Layer;

    fn workspace(crates: &[(&str, Layer)], edges: &[(&str, &str, DepKind)]) -> Workspace {
        Workspace {
            crates: crates.iter().map(|(n, l)| ((*n).to_string(), *l)).collect(),
            edges: edges
                .iter()
                .map(|(from, to, kind)| crate::layers::Edge {
                    from: (*from).to_string(),
                    to: (*to).to_string(),
                    kind: *kind,
                })
                .collect(),
        }
    }

    #[test]
    fn layers_are_drawn_in_stack_order_lowest_first() {
        let out = render(&workspace(
            &[
                ("leek-hir", Layer::Middle),
                ("leek-span", Layer::Core),
                ("miku", Layer::Bins),
            ],
            &[],
        ));
        let at = |needle: &str| {
            out.find(needle)
                .unwrap_or_else(|| panic!("{needle}\n{out}"))
        };
        assert!(at("subgraph core") < at("subgraph middle"), "{out}");
        assert!(at("subgraph middle") < at("subgraph bins"), "{out}");
    }

    /// Hyphens are mermaid operators, so a crate name cannot be a node id.
    #[test]
    fn crate_names_are_escaped_into_node_ids_and_kept_as_labels() {
        let out = render(&workspace(&[("leek-span", Layer::Core)], &[]));
        assert!(out.contains("leek_span[\"leek-span\"]"), "{out}");
    }

    /// Only normal edges are drawn — a dev-dependency reaching a layer up is
    /// legal and would misrepresent the stack.
    #[test]
    fn only_normal_dependencies_become_arrows() {
        let out = render(&workspace(
            &[
                ("leek-span", Layer::Core),
                ("leek-hir", Layer::Middle),
                ("leek-backend-native", Layer::Backends),
            ],
            &[
                ("leek-hir", "leek-span", DepKind::Normal),
                ("leek-hir", "leek-backend-native", DepKind::Dev),
            ],
        ));
        assert!(out.contains("leek_hir --> leek_span"), "{out}");
        assert!(
            !out.contains("leek_hir --> leek_backend_native"),
            "a dev edge was drawn:\n{out}"
        );
    }

    /// The render is a pure function of the graph, which is what makes the
    /// drift check meaningful: two runs over one workspace cannot differ.
    #[test]
    fn rendering_is_deterministic() {
        let ws = workspace(
            &[
                ("leek-span", Layer::Core),
                ("leek-hir", Layer::Middle),
                ("leek-mir", Layer::Middle),
            ],
            &[
                ("leek-mir", "leek-hir", DepKind::Normal),
                ("leek-hir", "leek-span", DepKind::Normal),
            ],
        );
        assert_eq!(render(&ws), render(&ws));
    }
}
