#!/usr/bin/env bash
# Extract the weapon and chip catalogs from the official leek-wars-generator
# data files (`data/weapons.json`, `data/chips.json`) into the committed
# generated Rust catalogs the fight engine uses
# (`crates/game/leek-game-runtime/src/{weapons_gen,chips_gen}.rs`).
#
# Each item's `effects` array is carried verbatim: the entry's `id` field is
# the generator's effect-type id (`Effect.TYPE_*` — NOT the `type` field),
# mapped to an engine `EffectKind` by `Effect::from_upstream` at compile time,
# so growing the engine's effect coverage never requires re-running this.
#
# Usage:
#   tools/game-item-extract.sh           # print both files to stdout
#   tools/game-item-extract.sh --check   # exit 1 if the committed files drift
#   tools/game-item-extract.sh --write   # overwrite the committed files

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DATA="$ROOT/official-generator/leek-wars-generator/data"
OUTDIR="$ROOT/crates/game/leek-game-runtime/src"

# emit weapons|chips — generate one catalog to stdout.
emit() {
  python3 - "$DATA" "$1" <<'PY'
import json
import sys

data_dir, which = sys.argv[1], sys.argv[2]
HEADER = "// GENERATED by tools/game-item-extract.sh --write — do not edit."


def num(v):
    """A JSON number as a Rust f64 literal."""
    f = float(v)
    return repr(int(f)) + ".0" if f == int(f) else repr(f)


def effects(item):
    out = []
    for e in item["effects"]:
        out.append(
            f"Effect::from_upstream({e['id']}, {num(e['value1'])}, "
            f"{num(e['value2'])}, {e['turns']}, {e['targets']}, "
            f"{e.get('modifiers', 0)})"
        )
    return "&[" + ", ".join(out) + "]"


def boolean(v):
    return "true" if bool(v) else "false"


if which == "weapons":
    items = json.load(open(f"{data_dir}/weapons.json"))
    print(HEADER)
    print("//")
    print("// The weapon catalog from the generator's `data/weapons.json`,")
    print("// keyed by the public `WEAPON_*` item id, sorted by item id.")
    print("#[rustfmt::skip]")
    print("static CATALOG: &[Weapon] = &[")
    for w in sorted(items.values(), key=lambda w: w["item"]):
        print(
            f'    Weapon {{ item: {w["item"]}, name: "{w["name"]}", '
            f'cost: {w["cost"]}, '
            f'min_range: {w["min_range"]}, max_range: {w["max_range"]}, '
            f'launch_type: {w["launch_type"]}, area: {w["area"]}, '
            f'los: {boolean(w["los"])}, '
            f'cooldown: {w.get("cooldown", 0)}, '
            f'max_uses: {w.get("max_uses", 0)}, '
            f'effects: {effects(w)} }},'
        )
    print("];")
else:
    items = json.load(open(f"{data_dir}/chips.json"))
    print(HEADER)
    print("//")
    print("// The chip catalog from the generator's `data/chips.json`, keyed")
    print("// by the public `CHIP_*` item id (the JSON key), sorted by id.")
    print("#[rustfmt::skip]")
    print("static CATALOG: &[Chip] = &[")
    for key, c in sorted(items.items(), key=lambda kv: int(kv[0])):
        print(
            f'    Chip {{ item: {int(key)}, name: "{c["name"]}", '
            f'cost: {c["cost"]}, '
            f'min_range: {c["min_range"]}, max_range: {c["max_range"]}, '
            f'launch_type: {c["launch_type"]}, area: {c["area"]}, '
            f'los: {boolean(c["los"])}, '
            f'cooldown: {c["cooldown"]}, '
            f'initial_cooldown: {c["initial_cooldown"]}, '
            f'team_cooldown: {boolean(c["team_cooldown"])}, '
            f'max_uses: {c.get("max_uses", 0)}, '
            f'effects: {effects(c)} }},'
        )
    print("];")
PY
}

case "${1:-}" in
  --write)
    emit weapons > "$OUTDIR/weapons_gen.rs"
    emit chips > "$OUTDIR/chips_gen.rs"
    echo "wrote $OUTDIR/weapons_gen.rs ($(grep -c 'Weapon {' "$OUTDIR/weapons_gen.rs") weapons)"
    echo "wrote $OUTDIR/chips_gen.rs ($(grep -c 'Chip {' "$OUTDIR/chips_gen.rs") chips)"
    ;;
  --check)
    ok=1
    diff -q <(emit weapons) "$OUTDIR/weapons_gen.rs" >/dev/null 2>&1 || ok=0
    diff -q <(emit chips) "$OUTDIR/chips_gen.rs" >/dev/null 2>&1 || ok=0
    if [ "$ok" = 0 ]; then
      echo "weapon/chip catalogs are out of date — run tools/game-item-extract.sh --write" >&2
      exit 1
    fi
    echo "weapon/chip catalogs up to date"
    ;;
  *)
    emit weapons
    emit chips
    ;;
esac
